// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	httptransport "github.com/go-openapi/runtime/client"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/igorskh/go-duolingo/client/achievements"
	"github.com/igorskh/go-duolingo/client/leaderboards"
	"github.com/igorskh/go-duolingo/client/login"
	"github.com/igorskh/go-duolingo/client/shop"
	"github.com/igorskh/go-duolingo/client/users"
)

// Default duolingo unofficial HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "www.duolingo.com"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http", "https"}

// NewHTTPClient creates a new duolingo unofficial HTTP client.
func NewHTTPClient(formats strfmt.Registry) *DuolingoUnofficial {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new duolingo unofficial HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *DuolingoUnofficial {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new duolingo unofficial client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *DuolingoUnofficial {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(DuolingoUnofficial)
	cli.Transport = transport
	cli.Achievements = achievements.New(transport, formats)
	cli.Leaderboards = leaderboards.New(transport, formats)
	cli.Login = login.New(transport, formats)
	cli.Shop = shop.New(transport, formats)
	cli.Users = users.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// DuolingoUnofficial is a client for duolingo unofficial
type DuolingoUnofficial struct {
	Achievements achievements.ClientService

	Leaderboards leaderboards.ClientService

	Login login.ClientService

	Shop shop.ClientService

	Users users.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *DuolingoUnofficial) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Achievements.SetTransport(transport)
	c.Leaderboards.SetTransport(transport)
	c.Login.SetTransport(transport)
	c.Shop.SetTransport(transport)
	c.Users.SetTransport(transport)
}
