// Code generated by go-swagger; DO NOT EDIT.

package leaderboards

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new leaderboards API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for leaderboards API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetLeaderboard returns user information when not logged in

User information when not logged in.
*/
func (a *Client) GetLeaderboard(params *GetLeaderboardParams, authInfo runtime.ClientAuthInfoWriter) (*GetLeaderboardOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetLeaderboardParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getLeaderboard",
		Method:             "GET",
		PathPattern:        "/leaderboards/{leaderboardID}/users/{userID}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetLeaderboardReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetLeaderboardOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetLeaderboardDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
