// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetXpSummariesParams creates a new GetXpSummariesParams object
// with the default values initialized.
func NewGetXpSummariesParams() *GetXpSummariesParams {
	var ()
	return &GetXpSummariesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetXpSummariesParamsWithTimeout creates a new GetXpSummariesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetXpSummariesParamsWithTimeout(timeout time.Duration) *GetXpSummariesParams {
	var ()
	return &GetXpSummariesParams{

		timeout: timeout,
	}
}

// NewGetXpSummariesParamsWithContext creates a new GetXpSummariesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetXpSummariesParamsWithContext(ctx context.Context) *GetXpSummariesParams {
	var ()
	return &GetXpSummariesParams{

		Context: ctx,
	}
}

// NewGetXpSummariesParamsWithHTTPClient creates a new GetXpSummariesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetXpSummariesParamsWithHTTPClient(client *http.Client) *GetXpSummariesParams {
	var ()
	return &GetXpSummariesParams{
		HTTPClient: client,
	}
}

/*GetXpSummariesParams contains all the parameters to send to the API endpoint
for the get xp summaries operation typically these are written to a http.Request
*/
type GetXpSummariesParams struct {

	/*Timezone
	  Time zone

	*/
	Timezone string
	/*UserID
	  UserID

	*/
	UserID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get xp summaries params
func (o *GetXpSummariesParams) WithTimeout(timeout time.Duration) *GetXpSummariesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get xp summaries params
func (o *GetXpSummariesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get xp summaries params
func (o *GetXpSummariesParams) WithContext(ctx context.Context) *GetXpSummariesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get xp summaries params
func (o *GetXpSummariesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get xp summaries params
func (o *GetXpSummariesParams) WithHTTPClient(client *http.Client) *GetXpSummariesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get xp summaries params
func (o *GetXpSummariesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTimezone adds the timezone to the get xp summaries params
func (o *GetXpSummariesParams) WithTimezone(timezone string) *GetXpSummariesParams {
	o.SetTimezone(timezone)
	return o
}

// SetTimezone adds the timezone to the get xp summaries params
func (o *GetXpSummariesParams) SetTimezone(timezone string) {
	o.Timezone = timezone
}

// WithUserID adds the userID to the get xp summaries params
func (o *GetXpSummariesParams) WithUserID(userID int64) *GetXpSummariesParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the get xp summaries params
func (o *GetXpSummariesParams) SetUserID(userID int64) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *GetXpSummariesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param timezone
	qrTimezone := o.Timezone
	qTimezone := qrTimezone
	if qTimezone != "" {
		if err := r.SetQueryParam("timezone", qTimezone); err != nil {
			return err
		}
	}

	// path param userID
	if err := r.SetPathParam("userID", swag.FormatInt64(o.UserID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
