// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/igorskh/go-duolingo/models"
)

// GetLeaderboardsLeaderboardIDUsersUserIDReader is a Reader for the GetLeaderboardsLeaderboardIDUsersUserID structure.
type GetLeaderboardsLeaderboardIDUsersUserIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLeaderboardsLeaderboardIDUsersUserIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLeaderboardsLeaderboardIDUsersUserIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetLeaderboardsLeaderboardIDUsersUserIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetLeaderboardsLeaderboardIDUsersUserIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetLeaderboardsLeaderboardIDUsersUserIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetLeaderboardsLeaderboardIDUsersUserIDOK creates a GetLeaderboardsLeaderboardIDUsersUserIDOK with default headers values
func NewGetLeaderboardsLeaderboardIDUsersUserIDOK() *GetLeaderboardsLeaderboardIDUsersUserIDOK {
	return &GetLeaderboardsLeaderboardIDUsersUserIDOK{}
}

/*GetLeaderboardsLeaderboardIDUsersUserIDOK handles this case with default header values.

A Users object.
*/
type GetLeaderboardsLeaderboardIDUsersUserIDOK struct {
	Payload *models.Leaderdoard
}

func (o *GetLeaderboardsLeaderboardIDUsersUserIDOK) Error() string {
	return fmt.Sprintf("[GET /leaderboards/{leaderboardID}/users/{userID}][%d] getLeaderboardsLeaderboardIdUsersUserIdOK  %+v", 200, o.Payload)
}

func (o *GetLeaderboardsLeaderboardIDUsersUserIDOK) GetPayload() *models.Leaderdoard {
	return o.Payload
}

func (o *GetLeaderboardsLeaderboardIDUsersUserIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Leaderdoard)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetLeaderboardsLeaderboardIDUsersUserIDBadRequest creates a GetLeaderboardsLeaderboardIDUsersUserIDBadRequest with default headers values
func NewGetLeaderboardsLeaderboardIDUsersUserIDBadRequest() *GetLeaderboardsLeaderboardIDUsersUserIDBadRequest {
	return &GetLeaderboardsLeaderboardIDUsersUserIDBadRequest{}
}

/*GetLeaderboardsLeaderboardIDUsersUserIDBadRequest handles this case with default header values.

The specified user ID or leaderboard ID is invalid (e.g. not a number).
*/
type GetLeaderboardsLeaderboardIDUsersUserIDBadRequest struct {
}

func (o *GetLeaderboardsLeaderboardIDUsersUserIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /leaderboards/{leaderboardID}/users/{userID}][%d] getLeaderboardsLeaderboardIdUsersUserIdBadRequest ", 400)
}

func (o *GetLeaderboardsLeaderboardIDUsersUserIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetLeaderboardsLeaderboardIDUsersUserIDNotFound creates a GetLeaderboardsLeaderboardIDUsersUserIDNotFound with default headers values
func NewGetLeaderboardsLeaderboardIDUsersUserIDNotFound() *GetLeaderboardsLeaderboardIDUsersUserIDNotFound {
	return &GetLeaderboardsLeaderboardIDUsersUserIDNotFound{}
}

/*GetLeaderboardsLeaderboardIDUsersUserIDNotFound handles this case with default header values.

A user with the specified ID was not found.
*/
type GetLeaderboardsLeaderboardIDUsersUserIDNotFound struct {
}

func (o *GetLeaderboardsLeaderboardIDUsersUserIDNotFound) Error() string {
	return fmt.Sprintf("[GET /leaderboards/{leaderboardID}/users/{userID}][%d] getLeaderboardsLeaderboardIdUsersUserIdNotFound ", 404)
}

func (o *GetLeaderboardsLeaderboardIDUsersUserIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetLeaderboardsLeaderboardIDUsersUserIDDefault creates a GetLeaderboardsLeaderboardIDUsersUserIDDefault with default headers values
func NewGetLeaderboardsLeaderboardIDUsersUserIDDefault(code int) *GetLeaderboardsLeaderboardIDUsersUserIDDefault {
	return &GetLeaderboardsLeaderboardIDUsersUserIDDefault{
		_statusCode: code,
	}
}

/*GetLeaderboardsLeaderboardIDUsersUserIDDefault handles this case with default header values.

Unexpected error
*/
type GetLeaderboardsLeaderboardIDUsersUserIDDefault struct {
	_statusCode int
}

// Code gets the status code for the get leaderboards leaderboard ID users user ID default response
func (o *GetLeaderboardsLeaderboardIDUsersUserIDDefault) Code() int {
	return o._statusCode
}

func (o *GetLeaderboardsLeaderboardIDUsersUserIDDefault) Error() string {
	return fmt.Sprintf("[GET /leaderboards/{leaderboardID}/users/{userID}][%d] GetLeaderboardsLeaderboardIDUsersUserID default ", o._statusCode)
}

func (o *GetLeaderboardsLeaderboardIDUsersUserIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
