// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLeaderboardsLeaderboardIDUsersUserIDParams creates a new GetLeaderboardsLeaderboardIDUsersUserIDParams object
// with the default values initialized.
func NewGetLeaderboardsLeaderboardIDUsersUserIDParams() *GetLeaderboardsLeaderboardIDUsersUserIDParams {
	var ()
	return &GetLeaderboardsLeaderboardIDUsersUserIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLeaderboardsLeaderboardIDUsersUserIDParamsWithTimeout creates a new GetLeaderboardsLeaderboardIDUsersUserIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLeaderboardsLeaderboardIDUsersUserIDParamsWithTimeout(timeout time.Duration) *GetLeaderboardsLeaderboardIDUsersUserIDParams {
	var ()
	return &GetLeaderboardsLeaderboardIDUsersUserIDParams{

		timeout: timeout,
	}
}

// NewGetLeaderboardsLeaderboardIDUsersUserIDParamsWithContext creates a new GetLeaderboardsLeaderboardIDUsersUserIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLeaderboardsLeaderboardIDUsersUserIDParamsWithContext(ctx context.Context) *GetLeaderboardsLeaderboardIDUsersUserIDParams {
	var ()
	return &GetLeaderboardsLeaderboardIDUsersUserIDParams{

		Context: ctx,
	}
}

// NewGetLeaderboardsLeaderboardIDUsersUserIDParamsWithHTTPClient creates a new GetLeaderboardsLeaderboardIDUsersUserIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLeaderboardsLeaderboardIDUsersUserIDParamsWithHTTPClient(client *http.Client) *GetLeaderboardsLeaderboardIDUsersUserIDParams {
	var ()
	return &GetLeaderboardsLeaderboardIDUsersUserIDParams{
		HTTPClient: client,
	}
}

/*GetLeaderboardsLeaderboardIDUsersUserIDParams contains all the parameters to send to the API endpoint
for the get leaderboards leaderboard ID users user ID operation typically these are written to a http.Request
*/
type GetLeaderboardsLeaderboardIDUsersUserIDParams struct {

	/*LeaderboardID
	  LeaderboardID

	*/
	LeaderboardID string
	/*UserID
	  UserID

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get leaderboards leaderboard ID users user ID params
func (o *GetLeaderboardsLeaderboardIDUsersUserIDParams) WithTimeout(timeout time.Duration) *GetLeaderboardsLeaderboardIDUsersUserIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get leaderboards leaderboard ID users user ID params
func (o *GetLeaderboardsLeaderboardIDUsersUserIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get leaderboards leaderboard ID users user ID params
func (o *GetLeaderboardsLeaderboardIDUsersUserIDParams) WithContext(ctx context.Context) *GetLeaderboardsLeaderboardIDUsersUserIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get leaderboards leaderboard ID users user ID params
func (o *GetLeaderboardsLeaderboardIDUsersUserIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get leaderboards leaderboard ID users user ID params
func (o *GetLeaderboardsLeaderboardIDUsersUserIDParams) WithHTTPClient(client *http.Client) *GetLeaderboardsLeaderboardIDUsersUserIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get leaderboards leaderboard ID users user ID params
func (o *GetLeaderboardsLeaderboardIDUsersUserIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLeaderboardID adds the leaderboardID to the get leaderboards leaderboard ID users user ID params
func (o *GetLeaderboardsLeaderboardIDUsersUserIDParams) WithLeaderboardID(leaderboardID string) *GetLeaderboardsLeaderboardIDUsersUserIDParams {
	o.SetLeaderboardID(leaderboardID)
	return o
}

// SetLeaderboardID adds the leaderboardId to the get leaderboards leaderboard ID users user ID params
func (o *GetLeaderboardsLeaderboardIDUsersUserIDParams) SetLeaderboardID(leaderboardID string) {
	o.LeaderboardID = leaderboardID
}

// WithUserID adds the userID to the get leaderboards leaderboard ID users user ID params
func (o *GetLeaderboardsLeaderboardIDUsersUserIDParams) WithUserID(userID string) *GetLeaderboardsLeaderboardIDUsersUserIDParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the get leaderboards leaderboard ID users user ID params
func (o *GetLeaderboardsLeaderboardIDUsersUserIDParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *GetLeaderboardsLeaderboardIDUsersUserIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param leaderboardID
	if err := r.SetPathParam("leaderboardID", o.LeaderboardID); err != nil {
		return err
	}

	// path param userID
	if err := r.SetPathParam("userID", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
