// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostLoginReader is a Reader for the PostLogin structure.
type PostLoginReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostLoginReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostLoginOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostLoginBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostLoginForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewPostLoginDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostLoginOK creates a PostLoginOK with default headers values
func NewPostLoginOK() *PostLoginOK {
	return &PostLoginOK{}
}

/*PostLoginOK handles this case with default header values.

Login successful
*/
type PostLoginOK struct {
}

func (o *PostLoginOK) Error() string {
	return fmt.Sprintf("[POST /login][%d] postLoginOK ", 200)
}

func (o *PostLoginOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostLoginBadRequest creates a PostLoginBadRequest with default headers values
func NewPostLoginBadRequest() *PostLoginBadRequest {
	return &PostLoginBadRequest{}
}

/*PostLoginBadRequest handles this case with default header values.

Invalid data
*/
type PostLoginBadRequest struct {
}

func (o *PostLoginBadRequest) Error() string {
	return fmt.Sprintf("[POST /login][%d] postLoginBadRequest ", 400)
}

func (o *PostLoginBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostLoginForbidden creates a PostLoginForbidden with default headers values
func NewPostLoginForbidden() *PostLoginForbidden {
	return &PostLoginForbidden{}
}

/*PostLoginForbidden handles this case with default header values.

Login failed
*/
type PostLoginForbidden struct {
}

func (o *PostLoginForbidden) Error() string {
	return fmt.Sprintf("[POST /login][%d] postLoginForbidden ", 403)
}

func (o *PostLoginForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostLoginDefault creates a PostLoginDefault with default headers values
func NewPostLoginDefault(code int) *PostLoginDefault {
	return &PostLoginDefault{
		_statusCode: code,
	}
}

/*PostLoginDefault handles this case with default header values.

Unexpected error
*/
type PostLoginDefault struct {
	_statusCode int
}

// Code gets the status code for the post login default response
func (o *PostLoginDefault) Code() int {
	return o._statusCode
}

func (o *PostLoginDefault) Error() string {
	return fmt.Sprintf("[POST /login][%d] PostLogin default ", o._statusCode)
}

func (o *PostLoginDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
