// Code generated by go-swagger; DO NOT EDIT.

package shop

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/igorskh/go-duolingo/models"
)

// GetShopItemListReader is a Reader for the GetShopItemList structure.
type GetShopItemListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetShopItemListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetShopItemListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetShopItemListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetShopItemListOK creates a GetShopItemListOK with default headers values
func NewGetShopItemListOK() *GetShopItemListOK {
	return &GetShopItemListOK{}
}

/*GetShopItemListOK handles this case with default header values.

A ShopItemList object.
*/
type GetShopItemListOK struct {
	Payload *models.ShopItemList
}

func (o *GetShopItemListOK) Error() string {
	return fmt.Sprintf("[GET /shop-items][%d] getShopItemListOK  %+v", 200, o.Payload)
}

func (o *GetShopItemListOK) GetPayload() *models.ShopItemList {
	return o.Payload
}

func (o *GetShopItemListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ShopItemList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetShopItemListDefault creates a GetShopItemListDefault with default headers values
func NewGetShopItemListDefault(code int) *GetShopItemListDefault {
	return &GetShopItemListDefault{
		_statusCode: code,
	}
}

/*GetShopItemListDefault handles this case with default header values.

Unexpected error
*/
type GetShopItemListDefault struct {
	_statusCode int
}

// Code gets the status code for the get shop item list default response
func (o *GetShopItemListDefault) Code() int {
	return o._statusCode
}

func (o *GetShopItemListDefault) Error() string {
	return fmt.Sprintf("[GET /shop-items][%d] getShopItemList default ", o._statusCode)
}

func (o *GetShopItemListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
