// Code generated by go-swagger; DO NOT EDIT.

package shop

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/igorskh/go-duolingo/models"
)

// PostShopItemListReader is a Reader for the PostShopItemList structure.
type PostShopItemListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostShopItemListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostShopItemListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPostShopItemListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostShopItemListOK creates a PostShopItemListOK with default headers values
func NewPostShopItemListOK() *PostShopItemListOK {
	return &PostShopItemListOK{}
}

/*PostShopItemListOK handles this case with default header values.

A ShopItemPurchased object.
*/
type PostShopItemListOK struct {
	Payload *models.ShopItemPurchased
}

func (o *PostShopItemListOK) Error() string {
	return fmt.Sprintf("[POST /shop-items][%d] postShopItemListOK  %+v", 200, o.Payload)
}

func (o *PostShopItemListOK) GetPayload() *models.ShopItemPurchased {
	return o.Payload
}

func (o *PostShopItemListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ShopItemPurchased)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostShopItemListDefault creates a PostShopItemListDefault with default headers values
func NewPostShopItemListDefault(code int) *PostShopItemListDefault {
	return &PostShopItemListDefault{
		_statusCode: code,
	}
}

/*PostShopItemListDefault handles this case with default header values.

Unexpected error
*/
type PostShopItemListDefault struct {
	_statusCode int
}

// Code gets the status code for the post shop item list default response
func (o *PostShopItemListDefault) Code() int {
	return o._statusCode
}

func (o *PostShopItemListDefault) Error() string {
	return fmt.Sprintf("[POST /shop-items][%d] postShopItemList default ", o._statusCode)
}

func (o *PostShopItemListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
