// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Achievements achievements
// swagger:model achievements
type Achievements struct {

	// achievements
	Achievements []*Achievement `json:"achievements"`
}

// Validate validates this achievements
func (m *Achievements) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAchievements(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Achievements) validateAchievements(formats strfmt.Registry) error {

	if swag.IsZero(m.Achievements) { // not required
		return nil
	}

	for i := 0; i < len(m.Achievements); i++ {
		if swag.IsZero(m.Achievements[i]) { // not required
			continue
		}

		if m.Achievements[i] != nil {
			if err := m.Achievements[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("achievements" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Achievements) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Achievements) UnmarshalBinary(b []byte) error {
	var res Achievements
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
