// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Course course
// swagger:model course
type Course struct {

	// author Id
	AuthorID string `json:"authorId,omitempty"`

	// crowns
	Crowns int64 `json:"crowns,omitempty"`

	// from language
	FromLanguage string `json:"fromLanguage,omitempty"`

	// health enabled
	HealthEnabled bool `json:"healthEnabled,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// learning language
	LearningLanguage string `json:"learningLanguage,omitempty"`

	// placement test available
	PlacementTestAvailable bool `json:"placementTestAvailable,omitempty"`

	// preload
	Preload bool `json:"preload,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// xp
	Xp int64 `json:"xp,omitempty"`
}

// Validate validates this course
func (m *Course) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Course) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Course) UnmarshalBinary(b []byte) error {
	var res Course
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
