// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CurrencyRewardBundlesRewardsItem currency reward bundles rewards item
// swagger:model currencyRewardBundlesRewardsItem
type CurrencyRewardBundlesRewardsItem struct {

	// amount
	Amount int64 `json:"amount,omitempty"`

	// consumed
	Consumed bool `json:"consumed,omitempty"`

	// currency
	Currency string `json:"currency,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// reward type
	RewardType string `json:"rewardType,omitempty"`
}

// Validate validates this currency reward bundles rewards item
func (m *CurrencyRewardBundlesRewardsItem) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CurrencyRewardBundlesRewardsItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CurrencyRewardBundlesRewardsItem) UnmarshalBinary(b []byte) error {
	var res CurrencyRewardBundlesRewardsItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
