// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GemsConfig gems config
// swagger:model gemsConfig
type GemsConfig struct {

	// gems
	Gems int64 `json:"gems,omitempty"`

	// gems per skill
	GemsPerSkill int64 `json:"gemsPerSkill,omitempty"`

	// use gems
	UseGems bool `json:"useGems,omitempty"`
}

// Validate validates this gems config
func (m *GemsConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GemsConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GemsConfig) UnmarshalBinary(b []byte) error {
	var res GemsConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
