// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Health health
// swagger:model health
type Health struct {

	// eligible for free refill
	EligibleForFreeRefill bool `json:"eligibleForFreeRefill,omitempty"`

	// health enabled
	HealthEnabled bool `json:"healthEnabled,omitempty"`

	// hearts
	Hearts int64 `json:"hearts,omitempty"`

	// max hearts
	MaxHearts int64 `json:"maxHearts,omitempty"`

	// seconds per heart segment
	SecondsPerHeartSegment int64 `json:"secondsPerHeartSegment,omitempty"`

	// seconds until next heart segment
	SecondsUntilNextHeartSegment int64 `json:"secondsUntilNextHeartSegment,omitempty"`

	// use health
	UseHealth bool `json:"useHealth,omitempty"`
}

// Validate validates this health
func (m *Health) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Health) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Health) UnmarshalBinary(b []byte) error {
	var res Health
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
