// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LastStreak last streak
// swagger:model lastStreak
type LastStreak struct {

	// days ago
	DaysAgo int64 `json:"daysAgo,omitempty"`

	// google play dev payload
	GooglePlayDevPayload string `json:"googlePlayDevPayload,omitempty"`

	// google play product Id
	GooglePlayProductID string `json:"googlePlayProductId,omitempty"`

	// is available for repair
	IsAvailableForRepair bool `json:"isAvailableForRepair,omitempty"`

	// last reached goal
	LastReachedGoal int64 `json:"lastReachedGoal,omitempty"`

	// length
	Length int64 `json:"length,omitempty"`

	// shortened product Id
	ShortenedProductID string `json:"shortenedProductId,omitempty"`
}

// Validate validates this last streak
func (m *LastStreak) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LastStreak) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LastStreak) UnmarshalBinary(b []byte) error {
	var res LastStreak
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
