// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Leaderdoard leaderdoard
// swagger:model leaderdoard
type Leaderdoard struct {

	// active
	Active *LeaderdoardActive `json:"active,omitempty"`

	// num sessions remaining to unlock
	NumSessionsRemainingToUnlock int64 `json:"num_sessions_remaining_to_unlock,omitempty"`

	// tier
	Tier int64 `json:"tier,omitempty"`
}

// Validate validates this leaderdoard
func (m *Leaderdoard) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateActive(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Leaderdoard) validateActive(formats strfmt.Registry) error {

	if swag.IsZero(m.Active) { // not required
		return nil
	}

	if m.Active != nil {
		if err := m.Active.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("active")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Leaderdoard) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Leaderdoard) UnmarshalBinary(b []byte) error {
	var res Leaderdoard
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
