// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LeaderdoardRanking leaderdoard ranking
// swagger:model leaderdoardRanking
type LeaderdoardRanking struct {

	// avatar url
	AvatarURL string `json:"avatar_url,omitempty"`

	// display name
	DisplayName string `json:"display_name,omitempty"`

	// score
	Score float64 `json:"score,omitempty"`

	// streak extended today
	StreakExtendedToday bool `json:"streak_extended_today,omitempty"`

	// user id
	UserID int64 `json:"user_id,omitempty"`
}

// Validate validates this leaderdoard ranking
func (m *LeaderdoardRanking) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LeaderdoardRanking) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LeaderdoardRanking) UnmarshalBinary(b []byte) error {
	var res LeaderdoardRanking
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
