// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LoginData login data
// swagger:model loginData
type LoginData struct {

	// distinct Id
	DistinctID string `json:"distinctId,omitempty"`

	// identifier
	Identifier string `json:"identifier,omitempty"`

	// landing Url
	LandingURL string `json:"landingUrl,omitempty"`

	// last referrer
	LastReferrer string `json:"lastReferrer,omitempty"`

	// password
	Password string `json:"password,omitempty"`
}

// Validate validates this login data
func (m *LoginData) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LoginData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LoginData) UnmarshalBinary(b []byte) error {
	var res LoginData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
