// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// OptionalFeature optional feature
// swagger:model OptionalFeature
type OptionalFeature struct {

	// id
	ID string `json:"id,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this optional feature
func (m *OptionalFeature) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OptionalFeature) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OptionalFeature) UnmarshalBinary(b []byte) error {
	var res OptionalFeature
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
