// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ShopItemPurchased shop item purchased
// swagger:model shopItemPurchased
type ShopItemPurchased struct {

	// id
	ID string `json:"id,omitempty"`

	// item name
	ItemName string `json:"itemName,omitempty"`

	// purchase date
	PurchaseDate int64 `json:"purchaseDate,omitempty"`

	// purchase Id
	PurchaseID string `json:"purchaseId,omitempty"`

	// purchase price
	PurchasePrice int64 `json:"purchasePrice,omitempty"`

	// quantity
	Quantity int64 `json:"quantity,omitempty"`

	// subscription info
	SubscriptionInfo *SubscriptionInfo `json:"subscriptionInfo,omitempty"`
}

// Validate validates this shop item purchased
func (m *ShopItemPurchased) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSubscriptionInfo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ShopItemPurchased) validateSubscriptionInfo(formats strfmt.Registry) error {

	if swag.IsZero(m.SubscriptionInfo) { // not required
		return nil
	}

	if m.SubscriptionInfo != nil {
		if err := m.SubscriptionInfo.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("subscriptionInfo")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ShopItemPurchased) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ShopItemPurchased) UnmarshalBinary(b []byte) error {
	var res ShopItemPurchased
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
