// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ShopItemList shop item list
// swagger:model shopItemList
type ShopItemList struct {

	// shop items
	ShopItems []*ShopItemListShopItemsItems0 `json:"shopItems"`
}

// Validate validates this shop item list
func (m *ShopItemList) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateShopItems(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ShopItemList) validateShopItems(formats strfmt.Registry) error {

	if swag.IsZero(m.ShopItems) { // not required
		return nil
	}

	for i := 0; i < len(m.ShopItems); i++ {
		if swag.IsZero(m.ShopItems[i]) { // not required
			continue
		}

		if m.ShopItems[i] != nil {
			if err := m.ShopItems[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("shopItems" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ShopItemList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ShopItemList) UnmarshalBinary(b []byte) error {
	var res ShopItemList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// ShopItemListShopItemsItems0 shop item list shop items items0
// swagger:model ShopItemListShopItemsItems0
type ShopItemListShopItemsItems0 struct {

	// currency type
	CurrencyType string `json:"currencyType,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// localized description
	LocalizedDescription string `json:"localizedDescription,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// price
	Price int64 `json:"price,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this shop item list shop items items0
func (m *ShopItemListShopItemsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ShopItemListShopItemsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ShopItemListShopItemsItems0) UnmarshalBinary(b []byte) error {
	var res ShopItemListShopItemsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
