// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SmartTip smart tip
// swagger:model smartTip
type SmartTip struct {

	// smart tip Id
	SmartTipID string `json:"smartTipId,omitempty"`

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this smart tip
func (m *SmartTip) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SmartTip) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SmartTip) UnmarshalBinary(b []byte) error {
	var res SmartTip
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
