// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// SubscriptionItem subscription item
// swagger:model SubscriptionItem
type SubscriptionItem struct {

	// has plus
	HasPlus bool `json:"hasPlus,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// monthly xp
	MonthlyXp int64 `json:"monthlyXp,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// picture
	Picture string `json:"picture,omitempty"`

	// total xp
	TotalXp int64 `json:"totalXp,omitempty"`

	// username
	Username string `json:"username,omitempty"`

	// weekly xp
	WeeklyXp int64 `json:"weeklyXp,omitempty"`
}

// Validate validates this subscription item
func (m *SubscriptionItem) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SubscriptionItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SubscriptionItem) UnmarshalBinary(b []byte) error {
	var res SubscriptionItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
