// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// XpGain xp gain
// swagger:model XpGain
type XpGain struct {

	// event type
	EventType string `json:"eventType,omitempty"`

	// skill Id
	SkillID string `json:"skillId,omitempty"`

	// time
	Time int64 `json:"time,omitempty"`

	// xp
	Xp int64 `json:"xp,omitempty"`
}

// Validate validates this xp gain
func (m *XpGain) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *XpGain) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *XpGain) UnmarshalBinary(b []byte) error {
	var res XpGain
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
