// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// XpSummary xp summary
// swagger:model xpSummary
type XpSummary struct {

	// daily goal xp
	DailyGoalXp int64 `json:"dailyGoalXp,omitempty"`

	// date
	Date int64 `json:"date,omitempty"`

	// frozen
	Frozen bool `json:"frozen,omitempty"`

	// gained xp
	GainedXp int64 `json:"gainedXp,omitempty"`

	// repaired
	Repaired bool `json:"repaired,omitempty"`

	// streak extended
	StreakExtended bool `json:"streakExtended,omitempty"`

	// user Id
	UserID int64 `json:"userId,omitempty"`
}

// Validate validates this xp summary
func (m *XpSummary) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *XpSummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *XpSummary) UnmarshalBinary(b []byte) error {
	var res XpSummary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
